### ISSUE TITLE
pivoting which way and when

### ISSUE THREAD

**Issue by DrMattG** [softloud/sysrevdata#36]
@softloud here is a link to my quick edit on the vignette but you will see where I am stuck https://github.com/softloud/sysrevdata/blob/machine_read/vignettes/Machine_readable.Rmd

**Comment by softloud** [comment]
So, are there two questions here? 

# how to pivot from long to wide

I'm fiddling with this this morning. Got curious about using regex to do it, 'cause at some point we have to shift to regex. Also just to get it done, it'll do for now, but we can keep learning better pivot functions and update.

- [ ] I'll make a comment in the code.

# structure 

When should we put the demonstrations? In what order? Yeah, I'm not sure about the outline structure.

**Comment by softloud** [comment]
On second thought, @DrMattG, if it's just dropping in some more code from the leaflet, if you point me to the line number I can totes do that. 

I thought you were reworking the text, but I should have clarified, rather than assumed, what the new bits you'd done were. 'Cause I think you're coding in the old version of the vignette. Anyways, I was confused, hence the pinging it over to you. 

We can zoom codejam it tomorrow first thing mebbe, wrap it up.
